# For a standalone version should be:
#
# fixtures:
#   forge_modules:
#     stdlib:
#       repo: "puppetlabs/stdlib"
#       ref:  "4.9.0"
#     filemapper:
#       repo: "adrien/filemapper"
#       ref:  "1.1.3"
#   symlinks:
#     l23network: "#{source_dir}"

fixtures:
  repositories:
    'stdlib': 'git://github.com/puppetlabs/puppetlabs-stdlib.git'
    'filemapper': 'git://github.com/adrienthebo/puppet-filemapper.git'
    'sysctl': 'git://github.com/duritong/puppet-sysctl.git'
  symlinks:
    'l23network': "#{source_dir}"