# For a standalone version should be:
#
fixtures:
  forge_modules:
    stdlib:
      repo: "puppetlabs/stdlib"
      ref:  "4.9.1"
    filemapper:
      repo: "adrien/filemapper"
      ref:  "1.1.3"
  symlinks:
    l23network: "#{source_dir}"
###
